-- MySQL Script generated by MySQL Workbench
-- Wed May 22 17:18:20 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Ethnic Cuisine`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Ethnic Cuisine` (
  `CU_ID` INT NOT NULL,
  `Name` VARCHAR(30) NOT NULL,
  `file_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`CU_ID`),
  UNIQUE INDEX `Name_UNIQUE` (`Name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Recipes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Recipes` (
  `REC_ID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(100) NOT NULL,
  `Pastry` TINYINT NULL DEFAULT 0,
  `Difficulty` INT NULL,
  `Desctiprion` VARCHAR(100) NULL,
  `Tip1` VARCHAR(150) NULL,
  `Tip2` VARCHAR(150) NULL,
  `Tip3` VARCHAR(150) NULL,
  `Total Time` INT NULL,
  `Prep Time` INT NULL,
  `Characrerization` VARCHAR(20) NULL,
  `PRIM_ING_ID` INT NOT NULL,
  `CU_ID` INT NOT NULL,
  `THEME_ID` INT NOT NULL,
  `file_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`REC_ID`),
  INDEX `test_idx` (`CU_ID` ASC) VISIBLE,
  CONSTRAINT `cuisine_recipe`
    FOREIGN KEY (`CU_ID`)
    REFERENCES `mydb`.`Ethnic Cuisine` (`CU_ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Ingredients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Ingredients` (
  `REC_ID` INT NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `Kcal per 100` INT NOT NULL,
  `FG_ID` INT NOT NULL,
  `File_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`REC_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Food Groups`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Food Groups` (
  `FG_ID` INT NOT NULL,
  `Name` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`FG_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Type` (
  `TY_ID` INT NOT NULL,
  `Meal_type` VARCHAR(20) NULL,
  PRIMARY KEY (`TY_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Label`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Label` (
  `LA_ID` INT NOT NULL,
  `Label_Info` VARCHAR(30) NULL,
  `file_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`LA_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Gear`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Gear` (
  `GR_ID` INT NOT NULL,
  `Name` VARCHAR(100) NULL,
  `Instructions` VARCHAR(500) NULL,
  `file_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`GR_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Steps`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Steps` (
  `REC_ID` INT NOT NULL,
  `Count` INT NOT NULL,
  `Step` VARCHAR(200) NULL,
  PRIMARY KEY (`REC_ID`, `Count`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Chefs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Chefs` (
  `CH_ID` INT NOT NULL,
  `First_Name` VARCHAR(15) NOT NULL,
  `Last_Name` VARCHAR(20) NOT NULL,
  `Phone` INT NOT NULL,
  `Birthday` INT NOT NULL,
  `Age` INT NULL,
  `Experience` INT NULL,
  `Class` INT NULL,
  `File_Name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`CH_ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Theme`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Theme` (
  `THEME_ID` INT NOT NULL,
  `Name` VARCHAR(30) NOT NULL,
  `Description` VARCHAR(500) NULL,
  `File_Name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`THEME_ID`),
  UNIQUE INDEX `Name_UNIQUE` (`Name` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Episodes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Episodes` (
  `EP_ID` INT NOT NULL,
  `Season` INT NOT NULL,
  `EP_Number` INT NOT NULL,
  `Winner` VARCHAR(36) NULL,
  `File_Name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`EP_ID`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
